#!/bin/sh
#/ Usage: script/totals
#/ Shows total hours for each year

set -e

mkdir -p .totals
for year in 20??; do
  find ${year}/ -name '*.txt' -type f -exec cat {} + > .totals/${year}.txt

  cat <<HEADER
------------------------------------------------------------------------
${year}
----
HEADER
  script/process --no-warn --historical --year ${year} .totals/${year}.txt
  echo ""
done
